apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.PersistentVolume.name }}
spec:
  storageClassName: {{ .Values.PersistentVolume.storageClassName }}
  capacity:
    storage: {{ .Values.PersistentVolume.storage }}
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: {{ .Values.PersistentVolume.hostPath }}