apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    run: my-redis
spec:
  type: NodePort
  selector:
    run: my-redis
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30010
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    run: my-app
spec:
  type: NodePort
  selector:
    run: my-app
  ports:
  - port: 8000
    name: app-port
    targetPort: 8000
    nodePort: 30008
    protocol: TCP
  - port: 6379
    name: redis-port
    targetPort: 6379
    nodePort: 30010
    protocol: TCP
  - port: 5672
    name: rabbit-port
    targetPort: 5672
    nodePort: 30012
    protocol: TCP