deployment:
  my_app_name: my-app
    replicas: 1
    repository: my_app
    tag: 1.0
    containerPort: 8000
    secret:
      name: SECRET_INFO
      secret_name: mysecret
      secret_key: app-secret