apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    run: my-redis
spec:
  type: NodePort
  selector:
    run: my-redis
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30010
    protocol: TCP